// 所有mutations的函数名放在这个文件里
export const SET_PROVINCE = 'SET_PROVINCE'
export const SET_STUDENTLIST = 'SET_STUDENTLIST'
export const SET_SLIDEFLAG = 'SET_SLIDEFLAG'
export const SET_TEACHERGROUPLIST = 'SET_TEACHERGROUPLIST'
export const SET_TEACHERNAME = 'SET_TEACHERNAME'
